"""initial schema

Revision ID: c501868f1334
Revises:
Create Date: 2026-08-27 11:24:46.223970
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from promo_bot.database.types import UTCDateTime

revision: str = "c501868f1334"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coupons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=160), nullable=True),
        sa.Column("store", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("starts_at", UTCDateTime(), nullable=True),
        sa.Column("ends_at", UTCDateTime(), nullable=True),
        sa.Column("discount_type", sa.String(length=20), nullable=True),
        sa.Column("discount_value", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("minimum_purchase", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("maximum_discount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("allowed_categories", sa.JSON(), nullable=False),
        sa.Column("allowed_products", sa.JSON(), nullable=False),
        sa.Column("account_restrictions", sa.Text(), nullable=True),
        sa.Column("app_only", sa.Boolean(), nullable=False),
        sa.Column("payment_restrictions", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=250), nullable=False),
        sa.Column("last_validated_at", UTCDateTime(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_coupons_status", "coupons", ["status"], unique=False)
    op.create_index("ix_coupons_store_code", "coupons", ["store", "code"], unique=False)
    op.create_table(
        "processed_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store", sa.String(length=32), nullable=False),
        sa.Column("external_product_id", sa.String(length=160), nullable=False),
        sa.Column("variation_key", sa.String(length=160), nullable=False),
        sa.Column("deal_hash", sa.String(length=128), nullable=False),
        sa.Column("last_sent_at", UTCDateTime(), nullable=True),
        sa.Column("last_price", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("last_coupon", sa.String(length=160), nullable=True),
        sa.Column("cooldown_until", UTCDateTime(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "store", "external_product_id", "variation_key", name="uq_processed_product_variation"
        ),
    )
    op.create_index("ix_processed_items_deal_hash", "processed_items", ["deal_hash"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=160), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=200), nullable=True),
        sa.Column("seller", sa.String(length=250), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("store", "external_id", name="uq_products_store_external_id"),
    )
    op.create_index(
        "ix_products_store_external_id", "products", ["store", "external_id"], unique=False
    )
    op.create_table(
        "source_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("message_id", sa.String(length=128), nullable=False),
        sa.Column("channel_id", sa.String(length=128), nullable=False),
        sa.Column("occurred_at", UTCDateTime(), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("links", sa.JSON(), nullable=False),
        sa.Column("processing_status", sa.String(length=40), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_summary", sa.String(length=500), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "message_id", "channel_id", name="uq_source_message"),
    )
    op.create_index(
        "ix_source_messages_status", "source_messages", ["processing_status"], unique=False
    )
    op.create_table(
        "deals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("previous_price", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("current_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("final_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("freight", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("coupon_id", sa.Integer(), nullable=True),
        sa.Column("payment_method", sa.String(length=32), nullable=False),
        sa.Column("installments", sa.Integer(), nullable=False),
        sa.Column("interest_free", sa.Boolean(), nullable=True),
        sa.Column("payment_condition", sa.Text(), nullable=True),
        sa.Column("discount_percent", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=250), nullable=False),
        sa.Column("discovery_origin", sa.String(length=40), nullable=False),
        sa.Column("discovered_at", UTCDateTime(), nullable=False),
        sa.Column("last_validated_at", UTCDateTime(), nullable=True),
        sa.Column("affiliate_link", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("send_status", sa.String(length=32), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["coupon_id"],
            ["coupons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_deals_discovered_at", "deals", ["discovered_at"], unique=False)
    op.create_index("ix_deals_last_validated_at", "deals", ["last_validated_at"], unique=False)
    op.create_index("ix_deals_status", "deals", ["status"], unique=False)
    op.create_table(
        "price_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("freight", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("payment_method", sa.String(length=32), nullable=False),
        sa.Column("installments", sa.Integer(), nullable=False),
        sa.Column("interest_free", sa.Boolean(), nullable=True),
        sa.Column("payment_condition", sa.Text(), nullable=True),
        sa.Column("collected_at", UTCDateTime(), nullable=False),
        sa.Column("source", sa.String(length=250), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_price_history_product_collected",
        "price_history",
        ["product_id", "collected_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_price_history_product_collected", table_name="price_history")
    op.drop_table("price_history")
    op.drop_index("ix_deals_status", table_name="deals")
    op.drop_index("ix_deals_last_validated_at", table_name="deals")
    op.drop_index("ix_deals_discovered_at", table_name="deals")
    op.drop_table("deals")
    op.drop_index("ix_source_messages_status", table_name="source_messages")
    op.drop_table("source_messages")
    op.drop_index("ix_products_store_external_id", table_name="products")
    op.drop_table("products")
    op.drop_index("ix_processed_items_deal_hash", table_name="processed_items")
    op.drop_table("processed_items")
    op.drop_index("ix_coupons_store_code", table_name="coupons")
    op.drop_index("ix_coupons_status", table_name="coupons")
    op.drop_table("coupons")
    # ### end Alembic commands ###
