"""Dependency-free domain model."""

from promo_bot.domain.enums import (
    AffiliateCandidateState,
    CapabilityStatus,
    ConfidenceLevel,
    CouponStatus,
    DealState,
    DeliveryState,
    DiscoveryOrigin,
    LinkSource,
    PaymentMethod,
    RelayLinkState,
    SourceMessageState,
    Store,
)
from promo_bot.domain.models import (
    Coupon,
    Deal,
    Money,
    PaymentCondition,
    PriceHistory,
    ProcessedItem,
    Product,
    SourceMessage,
)
from promo_bot.domain.state_machines import (
    StateTransitionError,
    ensure_affiliate_candidate_transition,
    ensure_deal_transition,
    ensure_delivery_transition,
    ensure_source_message_transition,
)

__all__ = [
    "AffiliateCandidateState",
    "CapabilityStatus",
    "ConfidenceLevel",
    "Coupon",
    "CouponStatus",
    "Deal",
    "DealState",
    "DeliveryState",
    "DiscoveryOrigin",
    "LinkSource",
    "Money",
    "PaymentCondition",
    "PaymentMethod",
    "PriceHistory",
    "ProcessedItem",
    "Product",
    "RelayLinkState",
    "SourceMessage",
    "SourceMessageState",
    "StateTransitionError",
    "Store",
    "ensure_affiliate_candidate_transition",
    "ensure_deal_transition",
    "ensure_delivery_transition",
    "ensure_source_message_transition",
]
